### PR TITLE
Isholiday additional args

### PR DESCRIPTION
**Pull request by delki8**
adding the possibility to pass additional args to holiday matchers so they can evaluate if it's a holiday or not based on other information, like localization.

### CODE REVIEW

**Comment by amaidah** [comment]
Hey @delki8, thanks for the PR.

I don't quite follow though. Do you have an example where passing extra data is useful for holiday matching? Localization is provided by luxon via time zone right so presumably that already exists and I've only thought of USA so far actually so I may just need an example to understand how it could be used.

**Comment by delki8** [comment]
@amaidah Sure, I can give you an example:

Due to local laws in Brazil, beyond national holidays, we can also have holidays by city or state. 

I'm now writing this app to compute vacation days for employees of a remote brazilian company. Since each one of them is working from a different city. When the algorithm is calculating the vacation days it needs to know if it is a holiday for the specific city or state where the employee lives.

**Comment by amaidah** [comment]
I see, that makes sense. 

I've cherry picked your commit and added it here along with tests & documentation: https://github.com/amaidah/luxon-business-days/pull/26

**Comment by amaidah** [comment]
This has been added: https://github.com/amaidah/luxon-business-days/releases/tag/v2.5.0

**Pull request closed without merging**
